Pagination implemented in erlcloud_ec2
alertlogic/erlcloud pull request #134
Opened 2016-11-11 14:57 UTC by SergeyOvchinnik

Problem:
7 erlcloud_ec2 describe functions with pagination implemented on API level did not support pagination feature on library level

Functions:
- describe_instances
- describe_instance_status
- describe_reserved_instance_offerings
- describe_snapshots
- describe_spot_fleet_instances
- describe_spot_price_history
- describe_tags

Solution:
Implemented pagination feature for all 7 functions
Implemented unit tests for pagination in those functions

Reviewers:
@ddosia @motobob

2016-11-11 21:14 UTC, motobob requested changes
several minor changes and it is finally good to go.

2016-11-11 21:14 UTC, motobob commented on src/erlcloud_ec2.erl
> +-type ok_error(Ok1, Ok2) :: {ok, Ok1, Ok2} | {error, term()}.
this seems to be 
```erlang
ok_error(Ok, ec2_token()) :: {ok, Ok, ec2_token()} | {error, term()}
```

2016-11-11 21:14 UTC, motobob commented on src/erlcloud_ec2.erl
> +                extract_results("DescribeInstanceStatusResponse", "instanceStatusSet", fun extract_instance_status/1, Doc),
please be consistent with line wrapping. pick one and use it everywhere

2016-11-11 21:14 UTC, motobob commented on src/erlcloud_ec2.erl
> +    InstanceTypes = proplists:get_value(instance_type, Selector),
technically speaking previous implementation allowed several `instance_type`s  or rest of the filters to be passed.
Please check with AWS API doc and make sure it's implemented accordingly

2016-11-11 21:14 UTC, motobob commented on src/erlcloud_ec2.erl
> +    InstanceTypes = proplists:get_value(instance_type, Selector),
same applies here.

2016-11-14 10:04 UTC, SergeyOvchinnik commented on src/erlcloud_ec2.erl
> +-type ok_error(Ok1, Ok2) :: {ok, Ok1, Ok2} | {error, term()}.
Well, `ok_error` is always parametrized as either `ok_error(proplist())` or `ok_error(proplist(), ec2_token())`, so I could just roll back to my previous implementation and not parametrize them at all. Doesn't make much difference for dialyzer anyway.

2016-11-14 10:09 UTC, SergeyOvchinnik commented on src/erlcloud_ec2.erl
> +    InstanceTypes = proplists:get_value(instance_type, Selector),
True, should have used `get_all_values` instead

2016-11-14 14:57 UTC, SergeyOvchinnik commented on src/erlcloud_ec2.erl
> +                extract_results("DescribeInstanceStatusResponse", "instanceStatusSet", fun extract_instance_status/1, Doc),
fixed

2016-11-14 14:57 UTC, SergeyOvchinnik commented on src/erlcloud_ec2.erl
> +    InstanceTypes = proplists:get_value(instance_type, Selector),
fixed

2016-11-14 14:57 UTC, SergeyOvchinnik commented on src/erlcloud_ec2.erl
> +    InstanceTypes = proplists:get_value(instance_type, Selector),
fixed

2016-11-15 01:29 UTC, motobob approved these changes
I'm out of comments. let's 🚢 :shipit: 
@ddosia are you fine?

2016-11-15 01:32 UTC, motobob commented
i actually wanted this to happen https://github.com/erlcloud/erlcloud/compare/master...SergeyOvchinnik:sovchinnik-erlcloud-ec2-pagination-feature but that's fine. we will merge it separatelly after

2016-11-15 16:09 UTC, ddosia approved these changes
+1

2016-11-15 16:09 UTC, ddosia commented on src/erlcloud_ec2.erl
> +-define(SPOT_INSTANCE_STATUS_MR_MAX, 1000).
Usually all "define"s are located somewhere in the top of the file.

2016-11-15 16:47 UTC, SergeyOvchinnik commented
I moved all defines and mutual types to the top, but defines don't look good at all. How would I optimize the so that the range is 5-1000 everywhere except the one place where it's 1-1000?

2016-11-16 11:12 UTC, merged